### PR TITLE
feat(diagnostics): support coc as source

### PR DESCRIPTION
**Pull request by xiyaowong**

### CODE REVIEW

**Comment by xiyaowong** [comment]
I forgot to create a new branch...

**Comment by akinsho** [comment]
@xiyaowong this looks good to me, I think it should be fine without a branch since I will squash and merge anyway. I'll test to make sure things aren't broken but will leave the verification of the `coc` logic to you since I don't use coc and don't really want to set it up just for this test case

**Comment by xiyaowong** [comment]
> @xiyaowong this looks good to me, I think it should be fine without a branch since I will squash and merge anyway. I'll test to make sure things aren't broken but will leave the verification of the `coc` logic to you since I don't use coc and don't really want to set it up just for this test case

The current logic is basically fine, because similar PR has been merged to nvim-tree before, which is stable at present

**Review by akinsho — CHANGES_REQUESTED** [review]
@xiyaowong just tried it out locally and got a crash using `nvim-lsp` due to a typo in the get all function name.

**Comment by xiyaowong** [comment]
@akinsho sorry for my carelessness. fixed

**Comment by akinsho** [comment]
Merged 👍🏿 thanks for contribution 🥇

**Pull request merged**
