### PR TITLE
fix(ui): Exclude hidden buffers from the list

### PR DESCRIPTION
**Pull request by mskelton**
When using the `always_show_bufferline` in conjunction with `null-ls` for formatting, the plugin will break the cursor location when formatting. This happens due to the fact that null-ls creates a temporary scratch buffer, runs the formatter, then destroys the temp buffer. In the middle of this, bufferline will see multiple buffers and for a moment attempt to render the bufferline, then hide it again. This seems to be breaking cursor position.

The fix I applied to this was to exclude hidden buffers from the total buffer count. I'm curious your thoughts on the implementation and if there would be any issues from this change.

### CODE REVIEW

**Comment by akinsho** [comment]
Hi @mskelton,

So I'm not sure what you mean by "breaking the cursor". I genuinely think there is literally no logic in this plugin that deals with the cursor position. If rendering a buffer in the tabline is causing changes to the cursor this seems like a bug in neovim

**Comment by mskelton** [comment]
Here is a screen recording showing the behavior. The first half is the broken behavior, the second half is the fixed behavior. The issues happens due `showtabline` briefly changing values then quickly changing back as a result of the extra temporary buffer.

https://github.com/akinsho/bufferline.nvim/assets/25914066/7731580b-c6eb-4754-88e8-61141fa06572

**Comment by akinsho** [comment]
Thanks for the video @mskelton, I still think the root cause here is neovim because I really don't understand how even quickly switching the value of `showtabline` would cause the cursor to move, this seems to me like a bug. Those things should be unrelated so the fact that one influences the other seems to be an issue.

**Comment by mskelton** [comment]
@akinsho It seems that bufferline is in part the culprit as loading neovim with any plugins or config and running `:set showtabline=2` doesn't change the cursor position.

https://github.com/akinsho/bufferline.nvim/assets/25914066/b3ce6061-4bf1-4600-9212-9677146eab54

**Pull request closed without merging**
