### PR TITLE
fix: always_show_bufferline should work in tabs mode

### LINKED ISSUE #371: Bufferline is not shown when mode == "tabs" and always_show_bufferline == false
When in `tabs` mode and flag `always_show_bufferline` is set to false, bufferline (tabline) is not shown because the check relies on number of buffers open, instead of relying on the number of tabs open:
https://github.com/akinsho/bufferline.nvim/blob/50e1bfe6f2c474c0a6e8171606b001f3b17ddeb2/lua/bufferline.lua#L123

Expected behavior:
Tabline shows when number of tabs is greater than 1, and hidden otherwise.

### PR DESCRIPTION
**Pull request by agorgl**
Fixes #371

### CODE REVIEW

**Review by akinsho — CHANGES_REQUESTED** [review]
@agorgl thanks for the PR this looks good to me I had a quick variable name change to suggest. I tried pushing it but can't add to this branch 
the diff is
```
diff --git a/lua/bufferline.lua b/lua/bufferline.lua
index 8f84179..6527f3c 100644
--- a/lua/bufferline.lua
+++ b/lua/bufferline.lua
@@ -120,8 +120,8 @@ end
 
 --- If the item count has changed and the next tabline status is different then update it
 function M.toggle_bufferline()
-  local nitems = config.options.mode == "tabs" and utils.get_tab_count() or utils.get_buf_count()
-  local status = (config.options.always_show_bufferline or nitems > 1) and 2 or 0
+  local item_count = config:is_tabline() and utils.get_tab_count() or utils.get_buf_count()
+  local status = (config.options.always_show_bufferline or item_count > 1) and 2 or 0
   if vim.o.showtabline ~= status then
     vim.o.showtabline = status
   end
```
I have convenience method for checking if it's a tabline which I think it's better to use here

**Comment by agorgl** [comment]
Fixed as suggested!

**Review by akinsho — CHANGES_REQUESTED** [review]
@agorgl thanks for making the tweaks, the tags file should not be added to version control though

**Comment by agorgl** [comment]
Ah sorry it was a blind git add, fixing

**Review by akinsho — APPROVED** [review]
LGTM 🚀 🥇 thanks

**Pull request merged**
