### PR TITLE
fix: convert user config highlights before merging

### PR DESCRIPTION
**Pull request by akinsho**
@booperlv can you please try this branch and see if it fixes your issue in #220

### CODE REVIEW

**Comment by booperlv** [comment]
Apologies for the late reply, it did work! For whatever reason though, it still does not update the colors of the bufferline when changing colors using custom highlights (used to have a `dofile` on the ColorScheme autocommand to solve this). It does solve the issue at hand though!

**Comment by akinsho** [comment]
@booperlv can you have another go with it? I think it should work correctly now.

**Comment by akinsho** [comment]
fixes #220

**Comment by akinsho** [comment]
Going to merge this since it's a bit of a blocker for anyone on 0.5 using the custom highlights, which isn't ideal. Let me know if you test this later and still have issues.

**Comment by booperlv** [comment]
Apologies for not being able to reply, was sleeping during that time. I'll update or create a new issue if I find anything at the end of the day! Thanks!

**Pull request merged**
