### PR TITLE
fix(offsets): use nvim_eval_statusline to calculate the size

### PR DESCRIPTION
**Pull request by xiyaowong**

### CODE REVIEW

**Comment by xiyaowong** [comment]
`strwidth` returns width of the raw text which includes expression, highlight. It's inaccurate

**Comment by akinsho** [comment]
Ah that makes sense @xiyaowong I hadn't expected anyone to put raw tabline components into that space

**Comment by akinsho** [comment]
@xiyaowong just to clarify have you also seen the that you can pass highlights to the custom area without adding them to the text e.g.
```lua
custom_areas = {
	return {{text = "this is text", guifg =  "#EC5241"}}
}
```

**Comment by xiyaowong** [comment]
yes, I known it

**Comment by xiyaowong** [comment]
image
This is my custom area

**Comment by akinsho** [comment]
@xiyaowong that API wasn't available in the stable nvim version, just FYI it would have broken for anyone using stable nvim

**Pull request merged**
