### PR TITLE
fix(offset): handle COLUMN layout types

### PR DESCRIPTION
**Pull request by Ursescu**

### CODE REVIEW

**Comment by Ursescu** [comment]
It's an attempt to fix #540 issue.

**Review by akinsho — APPROVED** [review]
LGTM 👍🏿 this appears to resolve all those issue, although I can't be certain if anything else is broken which is often the issue with this feature but will merge it into dev for now and see how it behaves

**Comment by Ursescu** [comment]
Can we integrate this into main branch?

**Comment by akinsho** [comment]
This was already integrated months ago. Dev used to get merged into main regularly. I don't use that workflow anymore but this was merged

**Pull request merged**
