### PR TITLE
feat: buffer groups

### PR DESCRIPTION
**Pull request by akinsho**
image

### With custom group separators and no highlights or icons
Screen Shot 2021-09-06 at 14 38 01

- [x] Highlight buffers according to group
- [x] Sort buffers according to group
- [x] Group icons
- [x] Group commands -
  - [x] `BufferLineGroupClose <completion>`
  - [x] lua API for acting on groups
- [x] Group separator components
- [x] Bugs
	- [x] highlights for thin style active buffer broken
	- [x] duplicated space on last group separator start 
- [x] Ensure feature is *entirely* opt-in 
- [x] documentation

- [x] tests

### CODE REVIEW

**Comment by akinsho** [comment]
bufferline_group_toggle

**Comment by ShiChenCong** [comment]
can i group file dynamic？when open file

**Comment by akinsho** [comment]
I'm not entirely sure I understand the request, but you have to define groups in advance you can't add them to a group if they don't match the group's definition

**Comment by ShiChenCong** [comment]
i mean, when open 3 buffer, i can` groupa: buffer 1, buffer 2, groupb: buffer 3`, not define on the config file

**Comment by akinsho** [comment]
@ShiChenCong, no, the feature is very new and there are still many things to *consider* adding, but currently buffers cannot be grouped dynamically by some command. I'm going to wait for things to stabilise and polish some rough edges before I think about adding any new grouping features.

**Pull request merged**
