### PR TITLE
refactor: use themable for all highlight settings

### PR DESCRIPTION
**Pull request by akinsho**
Unless there is a local preference,

this should fix @siduck's issue, but might break @jjc224 @denstiny issues again. Can you all test, please? It's probably most important that @denstiny and @jjc224's issues are fixed since this is the normal/advised usage of this component, so that should work. @siduck's usage is not recommended, so might not be fixable

### CODE REVIEW

**Comment by siduck** [comment]
@akinsho 
image

it doesnt work

**Comment by akinsho** [comment]
@siduck is `config.options.themable` set to true for you?

**Comment by siduck** [comment]
> @siduck is `config.options.themable` set to true for you?

yep

**Comment by akinsho** [comment]
Can you post the example test here again I don't have a reference to the original comment you made

**Comment by siduck** [comment]
> Can you post the example test here again I don't have a reference to the original comment you made

@akinsho 
```shell
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
 ```
```lua
require("packer").startup {
   {
      "wbthomason/packer.nvim",
      { "akinsho/bufferline.nvim", tag = "v2.*" },
      { "kyazdani42/nvim-web-devicons" },
   },
}

vim.opt.termguicolors = true
vim.opt.mouse = "a"

local bufferline = require "bufferline"

vim.cmd [[
 function! Quit_vim(a,b,c,d)
     qa
 endfunction
]]

-- config

bufferline.setup {
   options = {
      custom_areas = {
         right = function()
            return {
               { text = "%@Quit_vim@  %X" },
            }
         end,
      },
   },
}

local set_hl = vim.api.nvim_set_hl

-- works!

set_hl(0,   "BufferLineTabClose" , {
      bg = "#ffffff",
      fg = "#000000",
})

-- doesnt work :(

set_hl(0,"BufferLineRightCustomAreaText1" , {
      bg = "#f04040",
      fg = "#000000",
})
```

image

**Comment by akinsho** [comment]
Ok this should be fixed now.

**Comment by siduck** [comment]
@akinsho thanks for your time! works now 
image


Also I set the highlights out of bufferline config as it'd be easier to reload bufferline colors when I change themes on the fly ( with out telescope theme extension ) or I'd have to reload bufferline plugin too!

https://user-images.githubusercontent.com/59060246/168234204-f6bc775f-fa2e-4ce1-b752-18731c6d51d5.mp4

**Comment by jjc224** [comment]
> Unless there is a local preference,
> 
> this should fix @siduck's issue, but might break @jjc224 @denstiny issues again. Can you all test, please? It's probably most important that @denstiny and @jjc224's issues are fixed since this is the normal/advised usage of this component, so that should work. @siduck's usage is not recommended, so might not be fixable

Haven't ran into any issues. 👍 
Will let you know if I do.

**Pull request merged**
