### PR TITLE
fix(highlights): use correct background

### PR DESCRIPTION
**Pull request by casonadams**

### CODE REVIEW

**Comment by casonadams** [comment]
I am not quite sure what broke this test.  Would love to help debug if I can get some more details.

**Comment by akinsho** [comment]
@casonadams can you run the tests locally using `plenary` and see if there are actual failures locally. I think what you are seeing in CI here is an unrelated error.

**Comment by casonadams** [comment]
@akinsho running tests locally everything is passing.  How do I move forward?

**Comment by akinsho** [comment]
@casonadams that's good, nothing on your end I'll test the changes locally when I have time and merge them off they're ok

**Pull request merged**
