### PR TITLE
fix: 0.6.1 diagnostic deprecation warning #285

### LINKED ISSUE #285: [Bug]: vim.lsp.diagnostic.get_all is deprecated (nvim 0.6.1)
### What happened?

Screen Shot 2022-01-01 at 1 30 35 pm

Please see the attached screenshot. Started to receive this message constantly after upgrading neovim to 0.6.1

Can confirm this is caused by bufferline.nvim diagnostics. If I change the option `diagnostics=false` to disable diagnostics, this warning message goes away.

Probably caused by this [line](https://github.com/akinsho/bufferline.nvim/blob/de66766716ab29414c7dd078d16b4773ab53a0bd/lua/bufferline/diagnostics.lua#L90) from brief look.

### What did you expect to happen?

No warning message to be raised.

### Additional Information

Happy New Year BTW!

### commit

_No response_

### PR DESCRIPTION
**Pull request by kazhala**
This should fix #285 . Instead of checking 0.7 nightly, now just check if the version is greater than 0.6.1.

### CODE REVIEW

**Comment by bryant-the-coder** [comment]
nice :D

**Comment by mfiano** [comment]
Thank you! This was quite annoying.

**Comment by RayZ0rr** [comment]
Thanks.

Sorry if I am misunderstanding, but wouldn't a more general condition be more convenient? Like : 

`has('patch-<number>)` or `v:version > 800`

**Comment by bryant-the-coder** [comment]
when will akinsho merge it?

**Comment by kazhala** [comment]
Since its holiday seasons atm, expect delays. For now, you can simply disable LSP by setting `diagnostics=false` in the configuration which will remove the warning.

If you do really need the diagnostics, you can change the plugin from `use {'akinsho/bufferline.nvim', requires = 'kyazdani42/nvim-web-devicons'}` to `use {'kazhala/bufferline.nvim', requires = 'kyazdani42/nvim-web-devicons'}` and turn on notification for this repository. Once its merged, change it back.

**Review by akinsho — APPROVED** [review]
Thanks for the PR @kazhala 👍🏿 LGTM

**Comment by bryant-the-coder** [comment]
thank you thank you

**Pull request merged**
