### PR TITLE
refactor(ui): allow trunctation to follow direction

### LINKED ISSUE #413: Don't center tabs when scrolling
I always lose track of the buffer I am at because buffers get shifted all the time.

It is easier to show than explain.

Here's what it looks like in `bufferline.nvim`:
Peek 2022-05-11 08-33

Here's how it looks like in `barbar`:
Peek 2022-05-11 08-36

An option to change this setting would be nice.

### PR DESCRIPTION
**Pull request by akinsho**
This PR allows the current buffer to navigate till the end of the visible buffer line rather than always staying centered.

This PR fixes #413

### CODE REVIEW

**Comment by akinsho** [comment]
This is hard and probably needs a re-imagined mechanism for showing buffers

**Comment by tmerse** [comment]
Would love to see this happen. Any idea if this will land at some point?

**Comment by akinsho** [comment]
@tmerse I have no idea how to finish this PR, and in its current state it's probably no longer relevant. If you have any suggestions on implementation or can contribute a PR please feel free.

**Comment by tmerse** [comment]
Thanks for the quick reply. I am pretty swamped with work for now and the forseeable future.
I switched back from barbar to bufferline and I like else in bufferline better except it's hard for me to visually track the buffer, but it's a minor pain point.
If I manage to find the time, I'll have a look and see if I can come up with sth.

**Pull request closed without merging**
